name: Generate Snake Animation 🐍

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: flaviojr
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit e push da animação
        uses: EndBug/add-and-commit@v9
        with:
          message: 🐍 Atualiza snake.svg automaticamente
          add: 'dist/*'
